trying a more robust download-list

diff --git a/download-list b/download-list
--- a/download-list
+++ b/download-list
@@ -1,8 +1,15 @@
 #!/usr/bin/env bash
 
+# ----------------------------------------
+# User Config
+# ----------------------------------------
+MAX_RETRIES=5
+# ----------------------------------------
+
 # comment the above line and uncomment the next line to enable nvidia hw transcoding
 #youtube-dl -f bestvideo+bestaudio --recode-video mp4  -o  "%(channel)s - %(playlist)s - %(playlist_index)03d - %(title)s.%(ext)s" --postprocessor-args 'ffmpeg:-hwaccel cuda' "$@"
-/usr/local/bin/yt-dlp \
+
+CMD='/usr/local/bin/yt-dlp \
 -f bestvideo+bestaudio \
 --recode-video mp4 \
 -o  "%(channel)s - %(playlist)s - %(playlist_index)03d - %(title)s.%(ext)s" "$@" \
@@ -17,4 +24,20 @@
 --add-metadata \
 --write-description \
 --write-thumbnail \
---embed-thumbnail
+--embed-thumbnail'
+
+# DEBUG
+# CMD='mkdir whatever/not/available'
+
+RETRY=1
+eval $CMD "$@" 2>&1 # first try
+
+# DEBUG
+# echo "Exit code "$?""
+
+while [[ $?!=0 ]] && [[ $RETRY -lt $MAX_RETRIES ]];
+do
+    echo "Retry "$RETRY"..."
+    eval $CMD "$@" 2>&1
+    ((RETRY++))
+done
