now the loop stops retrying right after an exit code 0

diff --git a/download-video b/download-video
--- a/download-video
+++ b/download-video
@@ -1,19 +1,45 @@
 #!/usr/bin/env bash
 
+# ----------------------------------------
+# User Config
+# ----------------------------------------
+MAX_RETRIES=5
+# ----------------------------------------
+
 # comment the above line and uncomment the next line to enable nvidia hw transcoding
-#youtube-dl -f bestvideo+bestaudio --recode-video mp4 -o "%(channel)s - %(title)s.%(ext)s" --postprocessor-args 'ffmpeg:-hwaccel cuda' "$@"
-/usr/local/bin/yt-dlp \
--f bestvideo+bestaudio \
---recode-video mp4 -o  "%(channel)s - %(title)s - UPLOADED ON %(upload_date>%Y-%m-%d)s.%(ext)s" "$@" \
---download-archive downloaded.txt \
---retries 20 \
---retry-sleep exp=1:2 \
---fragment-retries 20 \
---file-access-retries 3 \
---sponsorblock-remove "all" \
---concurrent-fragments $(nproc) \
---no-check-certificate \
---add-metadata \
---write-description \
---write-thumbnail \
---embed-thumbnail
+#youtube-dl -f bestvideo+bestaudio --recode-video mp4  -o  "%(channel)s - %(playlist)s - %(playlist_index)03d - %(title)s.%(ext)s" --postprocessor-args 'ffmpeg:-hwaccel cuda' "$@"
+
+CMD='/usr/local/bin/yt-dlp
+-f bestvideo+bestaudio
+--recode-video mp4 -o  "%(channel)s - %(title)s - UPLOADED ON %(upload_date>%Y-%m-%d)s.%(ext)s" "$@"
+--download-archive downloaded.txt
+--retries 20
+--retry-sleep exp=1:2
+--fragment-retries 20
+--file-access-retries 3
+--sponsorblock-remove "all"
+--concurrent-fragments $(nproc)
+--no-check-certificate
+--add-metadata
+--write-description
+--write-thumbnail
+--embed-thumbnail'
+
+# DEBUG line
+# CMD='mkdir whatever/not/available'
+
+RETRY=1
+eval $CMD "$@" 2>&1 # first try
+
+# DEBUG line
+# echo "Exit code "$?""
+
+trap '{ echo "Quitting the script, leaving files untouched..." ; exit 1; }' INT
+while [[ $?!=0 ]] && [[ $RETRY -lt $MAX_RETRIES ]];
+do
+    # DEBUG line
+    # sleep 2
+    echo "Retry "$RETRY"..."
+    eval $CMD "$@" 2>&1
+    ((RETRY++))
+done
